spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_sso?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
